version: "3"
services:
  ganache: 
    image: trufflesuite/ganache-cli
    env_file: .env
    command: |
      ganache-cli \
        --account "0x$PRIVATE_KEY,10000000000000000000"
    ports:
      - 8545:8545
  db:
    image: postgres
    env_file: .env
    ports:
      - 5432:5432
